//! KSE-12 — property-based storage testing (MRFC-KSE-001 §18).
//!
//! Random operation sequences (create / update / delete / supersede /
//! relate / unrelate / snapshot / restore) are generated by a seeded
//! xorshift64* driver and executed against the real kernel on
//! AikoqlStorageEngine, wrapped in CountingEngine so the transactional-
//! atomicity invariant can count write batches per op. A reference model in
//! this file mirrors every committed state; after EVERY op the six §18
//! invariants are asserted:
//!
//!   1. no orphan relationships   — the derived key set (relo/reli/type) in
//!      the engine equals the model's exact image of it; any ghost row or
//!      missing row is drift, caught every op. (Index consistency, #6, is
//!      the same scan, so #1 and #6 share one global pin.)
//!   2. no duplicate logical IDs  — head/ rows have unique KOIDs.
//!   3. provenance completeness   — every head carries exactly one journal
//!      event per committed version (event_refs.len() == version, seqs
//!      strictly increasing).
//!   4. temporal consistency      — trace versions are exactly 1..=n,
//!      commit_ts non-decreasing, validity intervals never invert.
//!   5. transactional atomicity   — every successful kernel mutation lands
//!      in its fixed per-op-class number of write batches (1 for single
//!      commits); every FAILED op leaves 0 batches behind (no partial
//!      commit).
//!   6. index consistency         — see #1; the cadence sweep additionally
//!      runs the KSE-10 repair op and requires it to be a no-op.
//!
//! Per-op cost is bounded: #1/#2/#6 are global pins (derived-set scan +
//! head-scan uniqueness + batch count — all O(pool)), and #3/#4 are
//! asserted head-level (event count == version, event seqs increasing,
//! interval orientation) on a four-KO deterministic sample. The full-model
//! sweep every 97 ops (the same cadence PROP-001 uses for its
//! snapshot/restore cycle) adds the deep-lineage pins (trace: versions
//! exactly 1..=n, commit_ts non-decreasing — O(lineage²) decode, too heavy
//! per op), the ko/-version-row pins, the journal count pin, and the
//! rebuild no-op probe. Every panic names the seed and op index.
//!
//! Sizing: KSE12_NIGHTLY=1 → 10,000 sequences (the doc's nightly CI
//! minimum; the test fails if the env var is set but not honored — strict
//! opt-in, no silent short runs). Unset → 600-sequence CI smoke.

mod common;

use aikoql_kernel::storage::store::StorageEngine;
use aikoql_kernel::transaction::kernel::ManualClock;
use aikoql_kernel::{
    Direction, Evidence, EvidenceMethod, ForgetMode, Kernel, Metadata, PropertyMap,
    RelationshipRef, RememberRequest, Subject, SupersedeRequest, Value, KOID,
};
use aikoql_storage::AikoqlStorageEngine;
use common::{tmp, CountingEngine, LogicalCounts};
use std::collections::{BTreeSet, HashMap};
use std::sync::Arc;

const SEED: u64 = 0x12A0_0000;
const TYPE: &str = "prop_ko";
/// Live-object cap — keeps per-op checks O(pool) so 10,000 sequences stay
/// a nightly-sized job, not a weekend.
const CAP: usize = 28;
/// Full-model sweep + journal/version-row pins + rebuild no-op probe.
const SWEEP_AT: usize = 73;
/// Snapshot + checkpoint cadence (the doc's snapshot/restore op pair).
const SNAPSHOT_AT: usize = 96;
/// Period the two cadences share.
const PERIOD: usize = 97;

// ---------------------------------------------------------------------------
// Deterministic RNG (xorshift64*) — same driver as the kernel's qa2_prop.
// ---------------------------------------------------------------------------

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
    fn pct(&mut self) -> u64 {
        self.next() % 100
    }
}

// ---------------------------------------------------------------------------
// Reference model — mirrors every committed state.
// ---------------------------------------------------------------------------

#[derive(Clone)]
struct MKo {
    version: u64,
    props: PropertyMap,
    rels: Vec<(String, KOID, Direction)>,
    deleted: bool,
    superseded: bool,
}

#[derive(Clone)]
struct Model {
    kos: HashMap<KOID, MKo>,
    keys: Vec<KOID>,
}

impl Model {
    fn live(&self) -> Vec<KOID> {
        self.keys
            .iter()
            .copied()
            .filter(|k| !self.kos[k].deleted)
            .collect()
    }
}

fn ctx() -> aikoql_kernel::KnowledgeContext {
    aikoql_kernel::KnowledgeContext::new(Subject::new("alice"))
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect::<String>()
}

fn meta() -> Metadata {
    Metadata {
        type_name: TYPE.into(),
        tenant: None,
        schema_version: 1,
        tags: vec![],
    }
}

fn props(seq: u64) -> PropertyMap {
    let mut p = PropertyMap::new();
    p.insert("seq".into(), Value::Int(seq as i64));
    p
}

fn ev() -> Evidence {
    Evidence::new("kse12-prop", EvidenceMethod::DocExtraction)
}

/// The exact derived key set the model demands: for every head, one relo
/// and one reli row per edge (direction-swapped) plus one type row.
/// Drift against the engine scan is an orphan-relationship or index bug.
fn expected_derived(m: &Model) -> BTreeSet<Vec<u8>> {
    let mut out = BTreeSet::new();
    for (koid, mk) in &m.kos {
        for (t, target, dir) in &mk.rels {
            let (src, dst) = match dir {
                Direction::Outbound => (koid, target),
                Direction::Inbound => (target, koid),
            };
            let mut relo = b"relo/".to_vec();
            relo.extend_from_slice(src.as_bytes());
            relo.push(b'/');
            relo.extend_from_slice(t.as_bytes());
            relo.push(b'/');
            relo.extend_from_slice(dst.as_bytes());
            out.insert(relo);
            let mut reli = b"reli/".to_vec();
            reli.extend_from_slice(dst.as_bytes());
            reli.push(b'/');
            reli.extend_from_slice(t.as_bytes());
            reli.push(b'/');
            reli.extend_from_slice(src.as_bytes());
            out.insert(reli);
        }
        let mut tk = b"type/".to_vec();
        tk.extend_from_slice(TYPE.as_bytes());
        tk.push(b'/');
        tk.extend_from_slice(koid.as_bytes());
        out.insert(tk);
    }
    out
}

fn derived_keys(engine: &dyn StorageEngine) -> BTreeSet<Vec<u8>> {
    [
        b"relo/".as_slice(),
        b"reli/".as_slice(),
        b"type/".as_slice(),
    ]
    .into_iter()
    .flat_map(|p| engine.scan(p).unwrap())
    .map(|(k, _v)| k)
    .collect()
}

/// §18 invariant #2/#3/#4 for one KO: head agrees with the model, every
/// version has exactly one provenance event, the lineage is temporally
/// sound. THE per-KO check.
fn check_ko(k: &Kernel, m: &Model, koid: &KOID, op: usize) {
    let mk = &m.kos[koid];
    let head = k.get(ctx(), koid).unwrap_or_else(|e| {
        panic!(
            "seed {SEED:#x} op {op}: get {} failed: {e:?}",
            koid.to_hex()
        )
    });
    assert_eq!(
        head.version,
        mk.version,
        "seed {SEED:#x} op {op}: version mismatch on {}",
        koid.to_hex()
    );
    assert_eq!(
        head.properties,
        mk.props,
        "seed {SEED:#x} op {op}: props mismatch on {}",
        koid.to_hex()
    );
    let rels: Vec<(String, KOID)> = head
        .relationships
        .iter()
        .map(|r| (r.rel_type.clone(), r.target))
        .collect();
    let model_rels: Vec<(String, KOID)> = mk.rels.iter().map(|(t, d, _)| (t.clone(), *d)).collect();
    assert_eq!(
        rels,
        model_rels,
        "seed {SEED:#x} op {op}: relationships mismatch on {}",
        koid.to_hex()
    );
    assert_eq!(
        head.lifecycle.state == aikoql_kernel::LifecycleState::Deleted,
        mk.deleted,
        "seed {SEED:#x} op {op}: lifecycle mismatch on {}",
        koid.to_hex()
    );
    if mk.superseded {
        assert_eq!(
            head.epistemic_status(),
            aikoql_kernel::EpistemicStatus::Superseded,
            "seed {SEED:#x} op {op}: superseded KO lost its status"
        );
    }
    // #3 provenance: one event per committed version, in order.
    assert_eq!(
        head.event_refs.len(),
        mk.version as usize,
        "seed {SEED:#x} op {op}: provenance event count != version on {}",
        koid.to_hex()
    );
    assert!(
        head.event_refs.windows(2).all(|w| w[0].seq < w[1].seq),
        "seed {SEED:#x} op {op}: event seqs not strictly increasing on {}",
        koid.to_hex()
    );
    // #4 temporal (head level): intervals never invert.
    if let (Some(f), Some(t)) = (head.valid_from(), head.valid_to()) {
        assert!(
            f <= t,
            "seed {SEED:#x} op {op}: inverted interval [{f},{t}] on {}",
            koid.to_hex()
        );
    }
}

/// #4 temporal (deep lineage): every version exactly once in order
/// 1..=n, commit_ts never backwards. Trace decodes every version and
/// payloads grow with accumulated event refs — O(lineage²) per KO, so
/// this runs at the cadence sweep, not per op.
fn check_lineage(k: &Kernel, m: &Model, koid: &KOID, op: usize) {
    let mk = &m.kos[koid];
    let tr = k.trace(ctx(), koid).unwrap_or_else(|e| {
        panic!(
            "seed {SEED:#x} op {op}: trace {} failed: {e:?}",
            koid.to_hex()
        )
    });
    assert_eq!(
        tr.versions.len(),
        mk.version as usize,
        "seed {SEED:#x} op {op}: lineage length != version on {}",
        koid.to_hex()
    );
    assert!(
        tr.versions
            .windows(2)
            .all(|w| w[0].version + 1 == w[1].version),
        "seed {SEED:#x} op {op}: versions not exactly 1..=n on {}",
        koid.to_hex()
    );
    assert!(
        tr.versions
            .windows(2)
            .all(|w| w[0].commit_ts <= w[1].commit_ts),
        "seed {SEED:#x} op {op}: commit_ts ran backwards on {}",
        koid.to_hex()
    );
}

/// Per-op check: the derived-set pin (invariants #1 + #6, global), the
/// head-scan uniqueness pin (#2), and the four-KO deterministic sample
/// (#2/#3/#4 in depth).
fn check_after_op(k: &Kernel, engine: &dyn StorageEngine, m: &Model, rng: &mut Rng, op: usize) {
    assert_eq!(
        derived_keys(engine),
        expected_derived(m),
        "seed {SEED:#x} op {op}: derived index drifted (orphan or missing row)"
    );
    let heads: Vec<Vec<u8>> = engine
        .scan(b"head/")
        .unwrap()
        .into_iter()
        .map(|(k, _)| k)
        .collect();
    assert_eq!(
        heads.len(),
        heads.iter().collect::<BTreeSet<_>>().len(),
        "seed {SEED:#x} op {op}: duplicate logical ID in head/"
    );
    for _ in 0..4 {
        let koid = m.keys[rng.below(m.keys.len())];
        check_ko(k, m, &koid, op);
    }
}

/// Cadence sweep: every KO in full (head pins + deep lineage), the
/// ko/-version-row pins (#2), the journal count pin (#3), and the KSE-10
/// repair op as a no-op probe (#6 — any drift it would have repaired is
/// a failure, not a repair).
fn sweep(k: &Kernel, engine: &dyn StorageEngine, m: &Model, op: usize) {
    for koid in &m.keys {
        check_ko(k, m, koid, op);
        check_lineage(k, m, koid, op);
    }
    let heads: BTreeSet<Vec<u8>> = engine
        .scan(b"head/")
        .unwrap()
        .into_iter()
        .map(|(k, _)| k[5..].to_vec()) // head/<koid16> → the 16-byte KOID
        .collect();
    let mut seen = BTreeSet::new();
    for (key, _v) in engine.scan(b"ko/").unwrap() {
        // ko/<koid16><ts8> — no separator after the KOID (obj_key layout).
        assert_eq!(
            key.len(),
            3 + 16 + 8,
            "seed {SEED:#x} op {op}: malformed version key"
        );
        let koid = &key[3..19];
        assert!(
            heads.contains(koid),
            "seed {SEED:#x} op {op}: version row {} for a KOID ({}) with no head",
            hex(&key),
            hex(koid)
        );
        assert!(
            seen.insert(key.clone()),
            "seed {SEED:#x} op {op}: duplicate (koid, ts) version row"
        );
    }
    let events = engine.scan(b"ke/").unwrap().len();
    let versions: u64 = m.kos.values().map(|mk| mk.version).sum();
    assert_eq!(
        events as u64, versions,
        "seed {SEED:#x} op {op}: journal events != committed versions"
    );
    let report = k.rebuild_derived_indexes().unwrap();
    assert_eq!(
        (report.removed_stale, report.removed_invalid),
        (0, 0),
        "seed {SEED:#x} op {op}: rebuild found drift that per-op checks missed"
    );
    assert_eq!(
        derived_keys(engine),
        expected_derived(m),
        "seed {SEED:#x} op {op}: rebuild changed the derived set"
    );
}

// ---------------------------------------------------------------------------
// KSE-12 — 600-sequence CI smoke / 10,000-sequence nightly, all six
// invariants after every sequence.
// ---------------------------------------------------------------------------

#[test]
fn kse12_property_op_sequences_six_invariants_hold() {
    let nightly = std::env::var("KSE12_NIGHTLY")
        .map(|v| v == "1")
        .unwrap_or(false);
    let seqs = if nightly { 10_000 } else { 600 };
    // Strict opt-in: the env var must actually widen the run.
    assert_eq!(
        seqs >= 10_000,
        nightly,
        "KSE12_NIGHTLY set but the run did not honor it"
    );

    let engine = CountingEngine::new(Arc::new(
        AikoqlStorageEngine::open(tmp("kse12_prop")).unwrap(),
    ));
    let clock = Arc::new(ManualClock::new(10_000));
    let k = Kernel::open(engine.clone(), clock.clone(), SEED).unwrap();
    let snap = tmp("kse12_prop_snap");
    let mut rng = Rng(SEED);
    let mut m = Model {
        kos: HashMap::new(),
        keys: Vec::new(),
    };
    let mut seq = 0u64;
    let mut checkpoint: Option<Model> = None;

    for op in 0..seqs {
        clock.tick(rng.below(50) as u64 + 1);
        let batches_before = LogicalCounts::writes(&engine).0;
        let expected_batches: u64;
        let class: &'static str;

        if op % PERIOD == SNAPSHOT_AT {
            // snapshot: live backup + model checkpoint (the snapshot op of
            // the doc's list; restore lands in the random mix below).
            k.backup_store_to(&snap).unwrap();
            checkpoint = Some(m.clone());
            expected_batches = 0;
            class = "snapshot";
        } else {
            let roll = rng.pct();
            let live = m.live();
            let can_mutate = live.len() >= 2;
            if m.kos.is_empty() || (roll < 30 && m.keys.len() < CAP) {
                // create
                seq += 1;
                let mut r = RememberRequest::create(ctx(), meta());
                r.properties = props(seq);
                let rem = k.remember(r).unwrap();
                m.keys.push(rem.koid);
                m.kos.insert(
                    rem.koid,
                    MKo {
                        version: rem.version,
                        props: props(seq),
                        rels: vec![],
                        deleted: false,
                        superseded: false,
                    },
                );
                expected_batches = 1;
                class = "create";
            } else if roll < 40 && can_mutate {
                // update: new properties, relationships restated verbatim.
                let koid = live[rng.below(live.len())];
                seq += 1;
                let mut r = RememberRequest::update(ctx(), koid, meta());
                r.properties = props(seq);
                r.relationships = m.kos[&koid]
                    .rels
                    .iter()
                    .map(|(t, d, dir)| RelationshipRef {
                        rel_type: t.clone(),
                        target: *d,
                        direction: *dir,
                    })
                    .collect();
                let rem = k.remember(r).unwrap();
                let mk = m.kos.get_mut(&koid).unwrap();
                mk.version = rem.version;
                mk.props = props(seq);
                expected_batches = 1;
                class = "update";
            } else if roll < 48 && can_mutate {
                // relate: add one caller-owned edge.
                let src = live[rng.below(live.len())];
                let tgt = m.keys[rng.below(m.keys.len())];
                let mut r = RememberRequest::update(ctx(), src, meta());
                r.properties = m.kos[&src].props.clone();
                let mut rels = m.kos[&src].rels.clone();
                if !rels.iter().any(|(t, d, _)| t == "related_to" && *d == tgt) {
                    rels.push(("related_to".into(), tgt, Direction::Outbound));
                }
                r.relationships = rels
                    .iter()
                    .map(|(t, d, dir)| RelationshipRef {
                        rel_type: t.clone(),
                        target: *d,
                        direction: *dir,
                    })
                    .collect();
                let rem = k.remember(r).unwrap();
                let mk = m.kos.get_mut(&src).unwrap();
                mk.version = rem.version;
                mk.rels = rels;
                expected_batches = 1;
                class = "relate";
            } else if roll < 56 && can_mutate {
                // unrelate: drop the last caller-owned edge (kernel-managed
                // supersedes/derived_from/contradicts edges are carried
                // forward by the kernel and are not unrelate-eligible).
                let caller_owned =
                    |t: &str| t != "supersedes" && t != "derived_from" && t != "contradicts";
                let candidates: Vec<KOID> = live
                    .iter()
                    .copied()
                    .filter(|k| {
                        m.kos[k]
                            .rels
                            .last()
                            .map(|(t, _, _)| caller_owned(t))
                            .unwrap_or(false)
                    })
                    .collect();
                if let Some(&src) = candidates.get(rng.below(candidates.len().max(1))) {
                    let mut r = RememberRequest::update(ctx(), src, meta());
                    r.properties = m.kos[&src].props.clone();
                    let mut rels = m.kos[&src].rels.clone();
                    let pos = rels
                        .iter()
                        .rposition(|(t, _, _)| caller_owned(t))
                        .expect("candidate filter guarantees a caller-owned edge");
                    rels.remove(pos);
                    r.relationships = rels
                        .iter()
                        .map(|(t, d, dir)| RelationshipRef {
                            rel_type: t.clone(),
                            target: *d,
                            direction: *dir,
                        })
                        .collect();
                    let rem = k.remember(r).unwrap();
                    let mk = m.kos.get_mut(&src).unwrap();
                    mk.version = rem.version;
                    mk.rels = rels;
                    expected_batches = 1;
                    class = "unrelate";
                } else {
                    expected_batches = 0; // nothing to unrelate: query slot
                    class = "query";
                }
            } else if roll < 62 && can_mutate {
                // delete (tombstone): head survives, edges stay canonical.
                let koid = live[rng.below(live.len())];
                let f = k
                    .forget(ctx(), &koid, ForgetMode::Tombstone, None, None)
                    .unwrap();
                let mk = m.kos.get_mut(&koid).unwrap();
                mk.version = f.version;
                mk.deleted = true;
                expected_batches = 1;
                class = "delete";
            } else if roll < 70 && can_mutate {
                // supersede: old head closes, a successor generation opens.
                let candidates: Vec<KOID> = live
                    .iter()
                    .copied()
                    .filter(|k| !m.kos[k].superseded)
                    .collect();
                let Some(&koid) = candidates.get(rng.below(candidates.len().max(1))) else {
                    check_after_op(&k, engine.as_ref(), &m, &mut rng, op);
                    continue;
                };
                seq += 1;
                let mut req = SupersedeRequest::new(ctx(), koid, TYPE);
                req.properties = props(seq);
                req.evidence = vec![ev()];
                let res = k.supersede(req).unwrap();
                // The supersedes edge the kernel writes on the old head —
                // mirror its actual direction in the model.
                let head = k.get(ctx(), &koid).unwrap();
                let edge = head
                    .relationships
                    .iter()
                    .find(|r| r.rel_type == "supersedes" && r.target == res.new)
                    .expect("supersede must link old to successor");
                let old = m.kos.get_mut(&koid).unwrap();
                old.version += 1;
                old.superseded = true;
                old.rels
                    .push(("supersedes".into(), res.new, edge.direction));
                m.keys.push(res.new);
                m.kos.insert(
                    res.new,
                    MKo {
                        version: 1,
                        props: props(seq),
                        rels: vec![],
                        deleted: false,
                        superseded: false,
                    },
                );
                expected_batches = 2; // successor commit + old-head transition
                class = "supersede";
            } else if roll < 74 {
                // restore: roll the store back to the last snapshot; the
                // model rolls back with it. No snapshot yet → query slot.
                match &checkpoint {
                    Some(cp) => {
                        k.restore_store_from(&snap).unwrap();
                        m = cp.clone();
                        expected_batches = 1;
                        class = "restore";
                    }
                    None => {
                        expected_batches = 0;
                        class = "query";
                    }
                }
            } else if roll < 80 && can_mutate {
                // poisoned update: wrong expected version — the op must
                // fail and leave ZERO batches behind (failure atomicity).
                let koid = live[rng.below(live.len())];
                let mut r = RememberRequest::update(ctx(), koid, meta());
                r.properties = props(seq);
                r.expected_version = Some(m.kos[&koid].version + 77);
                assert!(
                    k.remember(r).is_err(),
                    "seed {SEED:#x} op {op}: poisoned update must fail"
                );
                expected_batches = 0;
                class = "poison";
            } else {
                expected_batches = 0; // query-only slot
                class = "query";
            }
        }

        // #5 transactional atomicity: exact per-op-class batch count.
        let batches = LogicalCounts::writes(&engine).0;
        assert_eq!(
            batches - batches_before,
            expected_batches,
            "seed {SEED:#x} op {op} ({class}): batch count {expected_batches} expected, \
             {} observed (partial commit?)",
            batches - batches_before
        );

        check_after_op(&k, engine.as_ref(), &m, &mut rng, op);
        if op % PERIOD == SWEEP_AT {
            sweep(&k, engine.as_ref(), &m, op);
        }
    }

    let _ = std::fs::remove_file(&snap);
    let _ = std::fs::remove_dir_all(&snap);
}
